import type { HomeFeatureCategory } from '@mahoshojo/ui-web/home';

/** Web 首页功能清单；不代表 Desktop 已交付或计划交付的功能。 */
export const HOME_FEATURE_CATEGORIES: readonly HomeFeatureCategory[] = [
  {
    id: 'character-generation',
    title: '~ 内容生成 ~',
    columns: 2,
    features: [
      {
        id: 'fairy-quest',
        assetFile: 'questionnaire-logo.svg',
        width: 320,
        height: 50,
        alt: '奇妙妖精大调查',
        href: '/details',
        className: 'fairy-quest',
      },
      {
        id: 'canshou-generator',
        assetFile: 'beast-logo-white.svg',
        width: 350,
        height: 50,
        alt: '危险残兽大调查',
        href: '/canshou',
        className: 'canshou-generator',
        onDark: true,
      },
      {
        id: 'magical-generator',
        assetFile: 'logo-white.svg',
        width: 320,
        height: 80,
        alt: '魔法少女生成器',
        href: '/name',
        className: 'magical-generator',
        onDark: true,
      },
      {
        id: 'scenario-generator',
        assetFile: 'scenario.webp',
        width: 350,
        height: 50,
        alt: '自定义情景生成',
        href: '/scenario',
        className: 'scenario-generator',
      },
    ],
  },
  {
    id: 'utilities',
    title: '~ 辅助功能 ~',
    columns: 2,
    features: [
      {
        id: 'free-generator',
        assetFile: 'free-generator-white.svg',
        width: 240,
        height: 100,
        alt: '自由生成',
        href: '/free',
        className: 'free-generator',
      },
      {
        id: 'character-party',
        assetFile: 'party-white.svg',
        width: 240,
        height: 100,
        alt: '角色组队',
        href: '/character-party',
        className: 'character-party',
        onDark: true,
      },
      {
        id: 'tavern-ecosystem',
        assetFile: 'tavern-white.svg',
        width: 240,
        height: 100,
        alt: '酒馆生态',
        href: '/tavern',
        className: 'tavern-ecosystem',
        onDark: true,
      },
      {
        id: 'magic-tea-party',
        assetFile: 'magic-tea-party-white.svg',
        width: 240,
        height: 100,
        alt: '魔法茶会',
        href: '/magic-tea-party',
        className: 'magic-tea-party',
        onDark: true,
      },
      {
        id: 'card-forge',
        assetFile: 'card-forge-white.svg',
        width: 240,
        height: 100,
        alt: '卡牌工坊',
        href: '/card-forge',
        className: 'card-forge',
        onDark: true,
      },
    ],
  },
  {
    id: 'battle',
    title: '~ 对战竞技 ~',
    columns: 1,
    features: [
      {
        id: 'battle-arena',
        assetFile: 'arena-white.svg',
        width: 240,
        height: 100,
        alt: '魔法少女竞技场',
        href: '/battle',
        className: 'battle-arena',
        onDark: true,
      },
    ],
  },
  {
    id: 'character-management',
    title: '~ 内容管理 ~',
    columns: 2,
    features: [
      {
        id: 'sublimation',
        assetFile: 'sublimation-white.svg',
        width: 350,
        height: 50,
        alt: '角色成长升华',
        href: '/sublimation',
        className: 'sublimation',
      },
      {
        id: 'character-manager',
        assetFile: 'character-manager-white.svg',
        width: 350,
        height: 50,
        alt: '角色数据管理',
        href: '/character-manager',
        className: 'character-manager',
      },
    ],
  },
];
