import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { arenaStreamMetaCases } from '../../../fixtures/arena-generation/stream-meta-input';
import {
  extractStreamUpdateMeta, extractStreamTelemetryMeta, findStreamUpdateMetaStart,
  stripStreamUpdateMetaComment, stripAllStreamMetaComments, splitStreamMeta,
} from '../src/arena-generation';

// Captured once from 2e0a35c0 Web source. Never regenerated by these tests.
const golden = JSON.parse(readFileSync(new URL('../../../fixtures/arena-generation/stream-meta-golden.json', import.meta.url), 'utf8'));
describe('shared stream metadata frozen legacy parity', () => {
  for (const fixture of arenaStreamMetaCases) {
    it(fixture.name, async () => {
      expect({
        start: findStreamUpdateMetaStart(fixture.raw),
        strip: stripStreamUpdateMetaComment(fixture.raw),
        markdown: stripAllStreamMetaComments(fixture.raw),
        update: await extractStreamUpdateMeta(fixture.raw).catch(error => ({ error: error.message })),
        telemetry: await extractStreamTelemetryMeta(fixture.raw),
      }).toEqual(golden[fixture.name]);
    });
  }
  it('splits all marker aliases in source order while retaining raw comments', () => {
    const fixture = arenaStreamMetaCases.find(value => value.name === 'multiple-markers-with-telemetry')!;
    const result = splitStreamMeta(fixture.raw);
    expect(result.markdown).toBe(golden[fixture.name].markdown);
    expect(result.updateMetaBlocks.map(value => value.marker)).toEqual(['MAHOSHOJO_META', 'MAHOSHOJO_STREAM_META']);
    expect(result.telemetryMetaBlocks).toHaveLength(1);
    for (const block of [...result.updateMetaBlocks, ...result.telemetryMetaBlocks]) {
      expect(fixture.raw).toContain(block.rawComment);
      expect(() => JSON.parse(block.jsonCandidate)).not.toThrow();
    }
    expect(JSON.parse(result.updateMetaBlocks.at(-1)!.jsonCandidate).report.headline).toBe('新');
  });
  it('keeps malformed and incomplete metadata out of the body without requiring repair', () => {
    const raw = '完整正文😀\n<!-- MAHOSHOJO_ARENA_META {unclosed:';
    expect(splitStreamMeta(raw)).toEqual({
      markdown: '完整正文😀',
      updateMetaBlocks: [{ rawComment: '<!-- MAHOSHOJO_ARENA_META {unclosed:', jsonCandidate: '{unclosed:', marker: 'MAHOSHOJO_ARENA_META' }],
      telemetryMetaBlocks: [],
    });
  });
  it('keeps source order when a closed update precedes a trailing incomplete update', () => {
    const old = '<!-- MAHOSHOJO_META {"report":{"headline":"旧"}} -->';
    const latest = '<!-- MAHOSHOJO_ARENA_META {report:{headline:"新"';
    const result = splitStreamMeta(`正文\n${old}\n中段\n${latest}`);
    expect(result.updateMetaBlocks.map(block => block.rawComment)).toEqual([old, latest]);
    expect(result.markdown).toBe('正文\n\n中段');
  });
  it('exposes the same inner candidate for malformed closed telemetry', () => {
    const result = splitStreamMeta('正文\n<!-- MAHOSHOJO_TELEMETRY_META : : : -->');
    expect(result.telemetryMetaBlocks[0]?.jsonCandidate).toBe('MAHOSHOJO_TELEMETRY_META : : :');
  });

});

it.each([
  ['MAHOSHOJO_ARENA_META', '"impacts":', 'updateMetaBlocks'],
  ['MAHOSHOJO_TELEMETRY_META', '"usage":', 'telemetryMetaBlocks'],
] as const)('isolates unfinished loose %s tails without changing the legacy wrapper', (marker, body, collection) => {
  const raw = `正文\n${marker} {${body}`;
  const split = splitStreamMeta(raw);
  expect(split.markdown).toBe('正文');
  expect(split[collection]).toHaveLength(1);
  expect(split[collection][0]!.rawComment).toContain(marker);
});

it('preserves source order for complete updates mixed with broken loose tails and Unicode indentation', () => {
  const complete = '<!-- MAHOSHOJO_META {"report":{"winner":"old"}} -->';
  const broken = '　--- mahoshojo_arena_meta {"impacts":';
  const telemetry = 'MAHOSHOJO_TELEMETRY_META {"usage":';
  const result = splitStreamMeta(`正文\n${complete}\n${broken}\n${telemetry}`);
  expect(result.markdown).toBe('正文');
  expect(result.updateMetaBlocks.map(block => block.rawComment.trim())).toEqual([complete, broken.trim()]);
  expect(result.telemetryMetaBlocks[0]?.rawComment).toBe(telemetry);
  // Reverse order still makes the later complete update effective.
  const reverse = splitStreamMeta(`正文\n${broken}\n${complete}`);
  expect(reverse.updateMetaBlocks.at(-1)?.rawComment).toBe(complete);
  expect(reverse.markdown).toBe('正文');
});
