fn main() {
    // D4a / DESK-012：自有 command 全部经 `AppManifest::commands` 纳入 ACL。
    // Tauri 默认让自定义 command 对所有本地 webview 可用；一旦声明了 app ACL
    // manifest，未登记的 command 会被拒绝——因此本清单必须保持与
    // `src/lib.rs` 的 `generate_handler!` 逐项一致。三方（generate_handler! ↔
    // 本清单 ↔ capabilities/main-ui.json 的 allow-*）一致性由
    // `tests/workspace-structure.test.ts` 的结构门禁钉住。
    //
    // 生成物落在 `permissions/autogenerated/<command>.toml`（allow-/deny- 各一），
    // 属于不入库的衍生资产（已 gitignore），不作为 ACL 事实来源——权威是上面的
    // 三方一致门禁。tauri-build 只写不清理，本地 build 后残留的 TOML 由结构门禁
    // 在目录存在时逐项比对抓出。
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "desktop_runtime_info",
            "set_provider_secret",
            "has_provider_secret",
            "delete_provider_secret",
            "save_provider_profile",
            "list_provider_profile_ids",
            "get_provider_profile",
            "delete_provider_profile",
            "validate_provider_execution_profile",
            "stream_direct_ai",
            "cancel_direct_ai",
            "save_local_card",
            "get_local_card",
            "list_local_cards",
            "delete_local_card",
            "restore_local_card",
            "purge_local_card",
            "save_web_package",
            "get_web_package",
            "list_web_packages",
            "delete_web_package",
            "restore_web_package",
            "purge_web_package",
            "read_web_package_archive",
            "begin_web_package_instance",
            "append_web_package_resource",
            "open_web_package_instance",
            "begin_local_archive_export",
            "append_local_archive_export_chunk",
            "audit_local_library",
            "create_local_backup",
            "list_local_backups",
            "prepare_local_restore",
            "exit_after_local_restore",
            "collect_local_garbage",
            "cloud_login_begin",
            "cloud_login_await",
            "cloud_login_cancel",
            "cloud_auth_status",
            "cloud_sign_out",
            "cloud_online_status",
            "stream_hosted_ai",
            "cloud_card_library_request",
            "cancel_hosted_ai",
        ]),
    ))
    .expect("failed to run tauri build script");
}
