export const USER_PROVIDED_KEY_COOLDOWN_MS = 3000;

export const OFFICIAL_KEY_QUESTIONNAIRE_CHARACTER_COOLDOWN_MS = 60000;
export const OFFICIAL_KEY_ARENA_BATTLE_REPORT_COOLDOWN_MS = 120000;

export const OFFICIAL_KEY_MAX_AI_COOLDOWN_MS = Math.max(
  OFFICIAL_KEY_QUESTIONNAIRE_CHARACTER_COOLDOWN_MS,
  OFFICIAL_KEY_ARENA_BATTLE_REPORT_COOLDOWN_MS
);

